//! Planner Agent - AI-powered task analysis and workflow generation
//!
//! Analyzes tasks via Claude CLI and generates dynamic execution plans
//! as workflow YAML that can be executed by ExecutionService.

use crate::cli::{CliManager, CliProvider, CliRequest};
use crate::error::CliError;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use uuid::Uuid;

/// Planner error type
#[derive(Debug, thiserror::Error)]
pub enum PlannerError {
    #[error("CLI execution failed: {0}")]
    Cli(#[from] CliError),

    #[error("Failed to parse plan JSON: {0}")]
    ParseError(String),

    #[error("Invalid plan structure: {0}")]
    InvalidPlan(String),

    #[error("YAML generation failed: {0}")]
    YamlError(String),
}

/// Execution plan generated by the Planner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// Task type classification
    pub task_type: String,
    /// Complexity score 1-10
    pub complexity: u8,
    /// Generated workflow YAML (ready for ExecutionService)
    pub workflow_yaml: String,
    /// Agent roles needed for this task
    pub required_roles: Vec<String>,
}

/// Intermediate JSON structure from Claude CLI response
#[derive(Debug, Clone, Serialize, Deserialize)]
struct PlanJson {
    task_type: String,
    complexity: u8,
    workflow_name: String,
    stages: Vec<PlanStage>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PlanStage {
    name: String,
    agent_id: String,
    agent_role: String,
    model: String,
    prompt: String,
    #[serde(default)]
    depends_on: Vec<String>,
    #[serde(default)]
    quality_gate: Option<PlanQualityGate>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PlanQualityGate {
    template: String,
    max_retries: usize,
}

/// Planner Agent - analyzes tasks and generates execution plans
pub struct Planner {
    cli_manager: Arc<CliManager>,
    provider: CliProvider,
}

impl Planner {
    pub fn new(cli_manager: Arc<CliManager>) -> Self {
        Self {
            cli_manager,
            provider: CliProvider::Claude,
        }
    }

    pub fn with_provider(cli_manager: Arc<CliManager>, provider: CliProvider) -> Self {
        Self {
            cli_manager,
            provider,
        }
    }

    /// Analyze a task and generate an execution plan
    pub async fn plan(&self, name: &str, description: &str) -> Result<ExecutionPlan, PlannerError> {
        let prompt = self.build_prompt(name, description);
        let request = CliRequest {
            provider: self.provider,
            prompt,
            system_prompt: Some(PLANNER_SYSTEM_PROMPT.to_string()),
            working_dir: None,
            env_vars: HashMap::new(),
            timeout_secs: Some(120),
            stream: false,
        };

        let response = self.cli_manager.execute(request).await?;
        let plan_json = self.parse_response(&response.text)?;
        let workflow_yaml = self.generate_workflow_yaml(&plan_json)?;

        Ok(ExecutionPlan {
            task_type: plan_json.task_type,
            complexity: plan_json.complexity.clamp(1, 10),
            workflow_yaml,
            required_roles: plan_json
                .stages
                .iter()
                .map(|s| s.agent_role.clone())
                .collect(),
        })
    }

    fn build_prompt(&self, name: &str, description: &str) -> String {
        format!(
            r#"你是任务规划专家。分析以下任务，输出 JSON 执行计划。

任务名称：{name}
任务描述：{description}

严格按以下 JSON 格式输出，不要附加任何其他文字：

{{
  "task_type": "bug_fix|feature|refactor|test|docs|research",
  "complexity": 1-10,
  "workflow_name": "auto-{uuid}",
  "stages": [
    {{
      "name": "分析",
      "agent_id": "analyzer",
      "agent_role": "Researcher",
      "model": "claude-sonnet-4-6",
      "prompt": "分析以下问题...",
      "depends_on": [],
      "quality_gate": null
    }},
    {{
      "name": "实现",
      "agent_id": "developer",
      "agent_role": "Developer",
      "model": "claude-sonnet-4-6",
      "prompt": "基于分析结果修复...",
      "depends_on": ["analyzer"],
      "quality_gate": {{"template": "rust_default", "max_retries": 2}}
    }}
  ]
}}"#,
            uuid = Uuid::new_v4()
        )
    }

    fn parse_response(&self, text: &str) -> Result<PlanJson, PlannerError> {
        // Try to extract JSON from response (may be wrapped in markdown code block)
        let json_str = if let Some(start) = text.find('{') {
            if let Some(end) = text.rfind('}') {
                &text[start..=end]
            } else {
                return Err(PlannerError::ParseError(
                    "No closing brace found".to_string(),
                ));
            }
        } else {
            return Err(PlannerError::ParseError(
                "No JSON object found in response".to_string(),
            ));
        };

        serde_json::from_str(json_str).map_err(|e| PlannerError::ParseError(e.to_string()))
    }

    fn generate_workflow_yaml(&self, plan: &PlanJson) -> Result<String, PlannerError> {
        // Build nexus_workflow::WorkflowDefinition-compatible YAML
        let mut yaml = String::new();
        yaml.push_str(&format!("name: \"{}\"\n", plan.workflow_name));
        yaml.push_str("version: \"1.0\"\n");
        yaml.push_str(&format!(
            "description: \"Auto-generated plan for: {}\"\n",
            plan.workflow_name
        ));
        yaml.push('\n');

        // Agents section
        yaml.push_str("agents:\n");
        for stage in &plan.stages {
            yaml.push_str(&format!(
                r#"  - id: "{}"
    role: "{}"
    model: "{}"
    prompt: |
      {}
    depends_on: {:?}
"#,
                stage.agent_id, stage.agent_role, stage.model, stage.prompt, stage.depends_on,
            ));
        }
        yaml.push('\n');

        // Stages section
        yaml.push_str("stages:\n");
        for stage in &plan.stages {
            yaml.push_str(&format!(
                r#"  - name: "{}"
    agents: ["{}"]
    parallel: false
    continue_on_error: false
"#,
                stage.name, stage.agent_id,
            ));

            if let Some(ref qg) = stage.quality_gate {
                yaml.push_str(&format!(
                    r#"    quality_gate:
      template: "{}"
      max_retries: {}
"#,
                    qg.template, qg.max_retries,
                ));
            }

            // Add next transitions for depends_on
            if !stage.depends_on.is_empty() {
                // Stages are sequential by default; depends_on is handled by agent ordering
            }
        }

        Ok(yaml)
    }
}

const PLANNER_SYSTEM_PROMPT: &str = r#"你是 NexusFlow 任务规划专家。你的职责是分析用户任务并生成结构化的执行计划。

规则：
1. 根据任务复杂度决定 stage 数量（简单任务 2-3 个，复杂任务 4-6 个）
2. 每个 stage 必须有明确的目标和 prompt
3. 合理使用质量门（quality_gate）确保代码质量
4. 按依赖关系排序 stages（先分析，再实现，最后验证）
5. 选择合适的模型（简单任务用 sonnet，复杂任务用 opus）
6. 输出严格 JSON，不要附加解释

可用的 agent_role：Researcher, Architect, Developer, Reviewer, Tester
可用的质量门模板：rust_default, typescript_default, python_default, go_default, docker_default"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_plan_json() {
        let json = r#"{
            "task_type": "bug_fix",
            "complexity": 5,
            "workflow_name": "auto-test",
            "stages": [
                {
                    "name": "分析",
                    "agent_id": "analyzer",
                    "agent_role": "Researcher",
                    "model": "claude-sonnet-4-6",
                    "prompt": "分析问题",
                    "depends_on": [],
                    "quality_gate": null
                }
            ]
        }"#;

        let plan: PlanJson = serde_json::from_str(json).unwrap();
        assert_eq!(plan.task_type, "bug_fix");
        assert_eq!(plan.complexity, 5);
        assert_eq!(plan.stages.len(), 1);
        assert_eq!(plan.stages[0].agent_id, "analyzer");
    }

    #[test]
    fn extract_json_from_markdown_block() {
        let text = "```json\n{\"task_type\":\"feature\",\"complexity\":3,\"workflow_name\":\"test\",\"stages\":[]}\n```";
        let json_str = &text[text.find('{').unwrap()..=text.rfind('}').unwrap()];
        let plan: PlanJson = serde_json::from_str(json_str).unwrap();
        assert_eq!(plan.task_type, "feature");
    }
}
